[theme]
# A modern blue for interactive widgets
primaryColor="#1E90FF"

# A dark gray, which is often more comfortable than pure black
backgroundColor="#0E1117"

# A slightly lighter dark gray for sidebars and other elements
secondaryBackgroundColor="#262730"

# Light text for high contrast and readability
textColor="#fafafa"

font="serif"

[server]
enableStaticServing = true
runOnSave = true
